[project]
name = "llms-txt-experiments"
version = "0.1.0"
description = "A content analysis of llms.txt files in the Common Crawl"
authors = [
  {name = "Malte Ostendorff", email = "malte@commoncrawl.org"},
]
readme = "README.md"
license = "Apache-2.0"
requires-python = ">=3.13"
dependencies = [
    "cdx-toolkit",
    "commonlid>=0.2.4",
    "datasets>=5.0.1",
    "fsspec[s3]>=2026.6.0",
    "jupyter>=1.1.1",
    "litellm>=1.95.0",
    "pandas>=3.0.5",
    "pyarrow>=25.0.0",
    "scikit-learn>=1.9.0",
    "uvloop>=0.22.1",
    "warcio[s3]>=1.8.1",
    "zstandard>=0.25.0",
]

[tool.uv]
# prevent uv from installing any new package 
# (give the community enough time to detect malware and yank)
exclude-newer = "7 days"

[tool.uv.sources]
cdx-toolkit = { git = "https://github.com/commoncrawl/cdx_toolkit", rev = "feat/warc-range-sources" }

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]

